application: hosted-canvas2d
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /html
  static_dir: html

- url: /
  script: ListDiagrams.py

- url: /login
  script: Login.py

- url: /home
  script: Home.py

- url: /start
  script: CreateDiagram.py

- url: /submit
  script: SubmitDiagram.py
  
- url: /api/user.*
  script: API.py

- url: /~.*
  script: ShowUser.py

- url: /.*[\.:](adl|json|js|script)
  script: ServeDiagram.py

- url: /.*
  script: ShowDiagram.py

builtins:
- datastore_admin: on
- remote_api: on
