application: hosted-canvas2d
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /
  script: ListDiagrams.py

- url: /login
  script: Login.py

- url: /load/diagrams
  script: LoadDiagrams.py

- url: /clear/diagrams
  script: ClearDiagrams.py

- url: /~.*
  script: ShowUser.py

- url: /.*
  script: ShowDiagram.py

builtins:
- datastore_admin: on
